name: aqary_tset
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/demo_data/
    - assets/images/